### ISSUE TITLE
Mapa mental 

### ISSUE THREAD

**Issue by 23620126** [SistemasTecTlaxiaco/actividad-4-mapa-mental-23620126#3]
[mapa mental 1.docx](https://github.com/SistemasTecTlaxiaco/actividad-4-mapa-mental-23620126/files/12681051/mapa.mental.1.docx)

**Comment by Felix-Angel** [comment]
Manejo conceptual: 22% (No identifico mínimo 8 elementos)
Relación entre los conjuntos: 25%
Calidad de la presentación: 22%
Jerarquía: 25%
Total 19.4/20
Evaluó equipo de Diego, Daniel, Félix Y Mayra.

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
